/**
 * SwapSheet — bottom-sheet UI for picking a swap source + destination.
 *
 * This screen is intentionally dumb. It pulls the list of Lightning
 * rails from the lightningSwap registry and renders one tile per rail.
 * Adding a 4th rail in the future = drop a provider in
 * src/services/lightningSwap/providers and the tile shows up here
 * automatically — no edits to this file.
 *
 * Source/destination state is held as the provider's `id`. Balances
 * for each rail come in via `balanceByProvider` (HomeScreen-owned state)
 * so the keyboard on the next screen can max-button correctly.
 */

import React, { useState } from "react";
import { View, TouchableOpacity, Image, Dimensions } from "react-native";
import LinearGradient from "react-native-linear-gradient";
import { Text } from "@Cypher/component-library";
import { GradientView } from "@Cypher/components";
import { colors } from "@Cypher/style-guide";
import { dispatchNavigate } from "@Cypher/helpers";
import { StyleSheet } from "react-native";

import {
    listLightningSwapProviders,
    type LightningSwapProvider,
    type LightningSwapProviderId,
} from "@Cypher/services/lightningSwap";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

interface Props {
    refSwapRBSheet: any;
    user: any;
    strikeMe: any;
    /**
     * Sats balance per rail. Keys are LightningSwapProviderId. Missing
     * keys default to 0. Owned by HomeScreen because the balances
     * already live there for the wallet cards — we just forward them.
     */
    balanceByProvider?: Partial<Record<LightningSwapProviderId, number>>;
}

export default function SwapSheet({
    refSwapRBSheet,
    user,
    strikeMe,
    balanceByProvider = {},
}: Props) {
    const providers = listLightningSwapProviders();

    const [swapFrom, setSwapFrom] = useState<LightningSwapProviderId | null>(null);
    const [sendTo, setSendTo] = useState<LightningSwapProviderId | null>(null);

    /**
     * When the user taps a source tile, auto-pick the destination as
     * the *first available* other provider — same convenience as the
     * old hardcoded Strike↔Coinos toggle, generalised. The user can
     * still override by tapping a destination tile.
     */
    const handleSelectFrom = (id: LightningSwapProviderId) => {
        setSwapFrom(id);
        if (sendTo === id) {
            const fallback = providers.find(
                p => p.id !== id && p.isAvailable(),
            );
            setSendTo(fallback ? fallback.id : null);
        }
    };
    const handleSelectTo = (id: LightningSwapProviderId) => {
        setSendTo(id);
        if (swapFrom === id) {
            const fallback = providers.find(
                p => p.id !== id && p.isAvailable(),
            );
            setSwapFrom(fallback ? fallback.id : null);
        }
    };

    const canProceed = swapFrom && sendTo && swapFrom !== sendTo;

    /**
     * Compose human-readable LN-address strings for the success view.
     * Existing flows pass these into SwapAmount as `fromAddress` /
     * `toAddress` for cosmetic display only — the actual swap goes via
     * BOLT11 invoices generated by the engine, not these addresses.
     *
     * Falls back to the providerId string when no canonical LN address
     * exists (Ark — non-custodial, no central directory; we just label
     * it with the displayName).
     */
    const lnAddressFor = (id: LightningSwapProviderId): string => {
        switch (id) {
            case 'coinos': return user ? `${user}@coinos.io` : 'coinos';
            case 'strike': return strikeMe?.username ? `${strikeMe.username}@strike.me` : 'strike';
            default: {
                const p = providers.find(x => x.id === id);
                return p?.displayName ?? id;
            }
        }
    };

    const handleNext = () => {
        if (!canProceed || !swapFrom || !sendTo) return;
        const sourceBalance = Number(balanceByProvider[swapFrom] || 0);
        refSwapRBSheet?.current?.close();
        dispatchNavigate('SwapAmount', {
            // Provider ids — the screen passes these to the engine.
            swapFrom,
            sendTo,
            // Cosmetic / display-only addresses.
            fromAddress: lnAddressFor(swapFrom),
            toAddress: lnAddressFor(sendTo),
            sourceBalance,
        });
    };

    /**
     * Render a single source/destination tile. Falls back to a text
     * label inside the gradient when the provider has no `icon` (Ark).
     */
    const renderTile = (
        provider: LightningSwapProvider,
        selected: boolean,
        onPress: () => void,
    ) => {
        const disabled = !provider.isAvailable();
        return (
            <GradientView
                key={provider.id}
                onPress={disabled ? undefined : onPress}
                style={styles.cardGradientStyle}
                linearGradientStyle={styles.cardOuterShadow}
                topShadowStyle={[
                    styles.cardTopShadow,
                    !selected && { shadowColor: colors.gray.disable },
                ]}
                bottomShadowStyle={[
                    styles.cardInnerShadow,
                    !selected && { shadowColor: colors.gray.disable },
                ]}
                linearGradientStyleMain={styles.cardGradientMainStyle}
                gradiantColors={[colors.black.bg, colors.black.bg]}
            >
                <View style={[styles.optionContent, disabled && { opacity: 0.4 }]}>
                    {provider.icon ? (
                        <Image
                            source={provider.icon}
                            style={styles.logoImage}
                            resizeMode="contain"
                        />
                    ) : (
                        // Text fallback for icon-less providers (Ark).
                        // Same height region as logoImage so tiles stay
                        // visually consistent in the row.
                        <Text bold style={styles.textBadge}>
                            {provider.displayName}
                        </Text>
                    )}
                </View>
            </GradientView>
        );
    };

    /**
     * Render the row of tiles for a section. With 2 providers we keep
     * the original space-evenly layout; with 3+ we wrap so the row
     * doesn't squeeze the tiles unreadably narrow on small screens.
     */
    const renderTileRow = (
        section: 'from' | 'to',
    ) => (
        <View style={styles.row}>
            {providers.map(p => {
                const selected =
                    section === 'from' ? swapFrom === p.id : sendTo === p.id;
                const onPress =
                    section === 'from'
                        ? () => handleSelectFrom(p.id)
                        : () => handleSelectTo(p.id);
                return renderTile(p, selected, onPress);
            })}
        </View>
    );

    return (
        <LinearGradient
            start={{ x: 0, y: 1 }}
            end={{ x: 1, y: 1 }}
            colors={[colors.pink.gradient1, colors.pink.gradient2]}
            style={styles.gradientLine}
        >
            <LinearGradient
                start={{ x: 1, y: 0 }}
                end={{ x: 1, y: 1 }}
                colors={[colors.black.gradientTop2, colors.black.default]}
                style={styles.containerGradientView}
            >
                <Text h2 bold style={styles.sectionTitle}>SWAP FROM</Text>
                {renderTileRow('from')}

                <Text h2 bold style={styles.sectionTitle}>SEND TO</Text>
                {renderTileRow('to')}

                <TouchableOpacity
                    onPress={handleNext}
                    disabled={!canProceed}
                    style={[
                        styles.nextBtn,
                        !canProceed && { backgroundColor: colors.gray.disable },
                    ]}
                >
                    <Text h3>Next</Text>
                </TouchableOpacity>
            </LinearGradient>
        </LinearGradient>
    );
}

// Tile width adapts to provider count. Two tiles use the original
// 0.4×SCREEN_WIDTH; three tiles squeeze to 0.28× to fit on a single
// row without wrap (looks better than wrapping at 3). Adjust the
// breakpoint if a 4th provider lands.
const TILE_WIDTH = SCREEN_WIDTH * 0.28;

const styles = StyleSheet.create({
    gradientLine: {
        width: "100%",
        borderRadius: 30,
        paddingTop: 3,
        flex: 1,
    },
    containerGradientView: {
        width: SCREEN_WIDTH,
        flex: 1,
        backgroundColor: colors.black.dark,
        borderRadius: 30,
    },
    sectionTitle: {
        alignSelf: "center",
        marginTop: 23,
    },
    row: {
        paddingHorizontal: 16,
        marginTop: 20,
        flexDirection: "row",
        justifyContent: "space-evenly",
        alignItems: "center",
        flexWrap: "wrap",
    },
    cardGradientStyle: {
        shadowColor: "#040404",
        shadowOffset: { width: 8, height: 8 },
        shadowOpacity: 0.8,
        shadowRadius: 16,
        elevation: 8,
        height: 67,
        width: TILE_WIDTH,
    },
    cardOuterShadow: {
        shadowColor: "#27272C",
        shadowOffset: { width: -8, height: -8 },
        shadowOpacity: 0.48,
        shadowRadius: 12,
        elevation: 8,
        flex: 1,
    },
    cardGradientMainStyle: {
        borderRadius: 25,
        height: 67,
        justifyContent: "center",
        alignItems: "center",
        width: TILE_WIDTH,
    },
    cardInnerShadow: {
        shadowOffset: { width: -2, height: -2 },
        shadowRadius: 2,
        shadowOpacity: 0.64,
        shadowColor: colors.pink.shadowBottom,
        borderRadius: 25,
        width: TILE_WIDTH,
        height: 67,
        justifyContent: "center",
        position: "absolute",
    },
    cardTopShadow: {
        shadowOffset: { width: 3, height: 3 },
        shadowColor: colors.pink.shadowTopNew,
        shadowRadius: 2,
        borderRadius: 25,
        width: TILE_WIDTH,
        height: 67,
        justifyContent: "center",
    },
    optionContent: {
        alignItems: "center",
        justifyContent: "center",
    },
    logoImage: {
        width: 80,
        height: 35,
    },
    textBadge: {
        // Same vertical footprint as logoImage so the tile center
        // aligns regardless of icon vs text rendering.
        height: 35,
        textAlignVertical: "center",
        textAlign: "center",
        fontSize: 18,
        color: colors.white,
    },
    nextBtn: {
        backgroundColor: colors.pink.light,
        height: 47,
        width: '80%',
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "center",
        marginTop: 40,
    },
});
