import React, { useEffect, useState } from "react";
import { ActivityIndicator, Image, View } from "react-native";

import { LeftArrow } from "@Cypher/assets/images";
import { ScreenLayout, Text } from "@Cypher/component-library";
import { GradientCard } from "@Cypher/components";
import { dispatchNavigate } from "@Cypher/helpers";
import {
    fetchArkMinBoardSats,
    getArkAddress,
    getArkOnchainAddress,
} from "@Cypher/services/ark";
import useAuthStore from "@Cypher/stores/authStore";
import { colors } from "@Cypher/style-guide";
import { useRoute } from "@react-navigation/native";

import { getFiatRate } from "../../../../models/fiatUnit";
import styles from "./styles";

/**
 * ArkReceiveScreen — Ark has three distinct receive methods, unlike the
 * CoinOS/Strike "lightning or on-chain" split. This screen is the router:
 *
 *   1. Ark address — instant VTXO-level transfer from another Ark user.
 *      No amount required; the receiver picks the invoice in the next step.
 *   2. Bitcoin on-chain — board funds into the Ark wallet. Uses the shared
 *      BDK on-chain wallet (`ensureArkOnchainHandle`). No amount required.
 *   3. Lightning invoice — BOLT11 generated by Ark's server (requires an
 *      amount, goes through `ArkInvoiceScreen` for entry).
 *
 * Methods 1 and 2 resolve the address up front and hand off to the existing
 * `CopyInvoice` screen (which is already generic over value/converted/hash).
 */
export default function ArkReceiveScreen() {
    // ReceivedListNew passes `{ matchedRate, currency }` here when routing
    // to the Ark receive sub-menu — but those values come from
    // `matchedRateStrike` + Strike's account currency, which means an Ark
    // user with a Strike-EUR account would see the Ark invoice priced in
    // EUR using Strike's exchange rate. Bam asked for two corrections:
    //   1. Currency: EUR only if a Strike account is connected AND its
    //      profile currency is EUR; otherwise USD. (No Strike connected →
    //      always USD, regardless of what was passed in.)
    //   2. Rate: pulled fresh from BlueWallet's `getFiatRate` for the
    //      target currency rather than reusing Strike's API rate or the
    //      CoinOS-derived `matchedRate` from upstream.
    // We resolve both at navigation time so the values are current and the
    // logic stays out of ArkInvoiceScreen (which is keyboard-only).
    useRoute<any>(); // route params are intentionally ignored — see above
    const { isStrikeAuth, strikeUser } = useAuthStore();
    const [loading, setLoading] = useState<null | "ark" | "onchain">(null);
    const [error, setError] = useState<string | null>(null);
    // Live server minimum board amount, for the on-chain deposit warning. A
    // deposit below this confirms on-chain but can never be boarded into a
    // VTXO (the ASP rejects it), so warn the user before they share the
    // boarding address. 50k sats fallback if arkInfo is unreachable.
    const [minBoardSats, setMinBoardSats] = useState(50000);
    useEffect(() => {
        let cancelled = false;
        fetchArkMinBoardSats().then(min => {
            if (!cancelled && typeof min === 'number' && min > 0) setMinBoardSats(min);
        });
        return () => { cancelled = true; };
    }, []);

    const handleArkAddress = async () => {
        setLoading("ark");
        setError(null);
        try {
            const address = await getArkAddress();
            dispatchNavigate("CopyInvoice", {
                value: "Bark address",
                converted: "",
                hash: address,
                receiveType: false,
            });
        } catch (err) {
            setError((err as Error)?.message ?? "Failed to get Bark address");
        } finally {
            setLoading(null);
        }
    };

    const handleOnchainAddress = async () => {
        setLoading("onchain");
        setError(null);
        try {
            const address = await getArkOnchainAddress();
            dispatchNavigate("CopyInvoice", {
                value: "Bitcoin address",
                converted: "Board funds into Bark",
                hash: address,
                receiveType: false,
            });
        } catch (err) {
            setError((err as Error)?.message ?? "Failed to get on-chain address");
        } finally {
            setLoading(null);
        }
    };

    const handleLightning = async () => {
        // EUR only when Strike is connected and its profile currency is
        // EUR — otherwise default to USD.
        const strikeCurrency = strikeUser?.[1]?.currency;
        const targetCurrency =
            isStrikeAuth && strikeCurrency === "EUR" ? "EUR" : "USD";

        // CustomKeyboard's conversion formula uses `sats / SATS *
        // matchedRate`, which only resolves to fiat correctly when
        // matchedRate is currency-per-BTC. Strike's `matchedRateStrike`
        // (used by every other invoice flow) is also stored per-BTC, so
        // we match that convention here. Earlier I converted to per-sat
        // by `* btc(1)` — that gave a fiat output 1e-8× too small, which
        // showed as 0.00. Pass the raw `getFiatRate` value (per-BTC).
        let rate = 0;
        try {
            const perBtc = await getFiatRate(targetCurrency);
            rate = Number(perBtc) || 0;
        } catch (_) {
            rate = 0;
        }

        dispatchNavigate("ArkInvoiceScreen", {
            matchedRate: rate,
            currency: targetCurrency,
        });
    };

    const busy = loading !== null;

    return (
        <ScreenLayout showToolbar isBackButton>
            <View style={styles.container}>
                <View style={styles.innerView}>
                    <Text subHeader bold>🐶 Receive to Bark</Text>

                    <View style={styles.extra} />
                    <GradientCard
                        style={styles.height}
                        linearStyle={styles.height}
                        onPress={busy ? undefined : handleArkAddress}
                    >
                        <View style={styles.background}>
                            <View style={styles.view}>
                                <View style={styles.container2}>
                                    <Text subHeader bold style={styles.title}>Bark address</Text>
                                    <Text h4 bold style={styles.desc}>
                                        Instant VTXO capsule transfer from another Bark user.
                                        No fees, no confirmations.
                                    </Text>
                                </View>
                                <Image source={LeftArrow} style={styles.image} resizeMode="contain" />
                            </View>
                        </View>
                    </GradientCard>

                    <View style={styles.extra} />
                    <GradientCard
                        style={styles.height}
                        linearStyle={styles.height}
                        onPress={busy ? undefined : handleLightning}
                    >
                        <View style={styles.background}>
                            <View style={styles.view}>
                                <View style={styles.container2}>
                                    <Text subHeader bold style={styles.title}>Lightning invoice</Text>
                                    <Text h4 bold style={styles.desc}>
                                        BOLT11 invoice via the Bark server. Works with any
                                        Lightning wallet.
                                    </Text>
                                </View>
                                <Image source={LeftArrow} style={styles.image} resizeMode="contain" />
                            </View>
                        </View>
                    </GradientCard>

                    <View style={styles.extra} />
                    <GradientCard
                        style={styles.height}
                        linearStyle={styles.height}
                        onPress={busy ? undefined : handleOnchainAddress}
                    >
                        <View style={styles.background}>
                            <View style={styles.view}>
                                <View style={styles.container2}>
                                    <Text subHeader bold style={styles.title}>Bitcoin on-chain</Text>
                                    <Text h4 bold style={styles.desc}>
                                        Deposit to a bitcoin address, then board the funds
                                        into your Bark balance.
                                    </Text>
                                    <Text style={{ color: '#FFD54F', fontSize: 12, marginTop: 6, fontWeight: '600' }}>
                                        Minimum {minBoardSats} sats. Smaller deposits can't be boarded into Bark and would have to be recovered on-chain.
                                    </Text>
                                </View>
                                <Image source={LeftArrow} style={styles.image} resizeMode="contain" />
                            </View>
                        </View>
                    </GradientCard>

                    {error && <Text style={styles.errorText}>{error}</Text>}
                </View>

                {busy && (
                    <View style={styles.loadingOverlay} pointerEvents="auto">
                        <ActivityIndicator size="large" color={colors.ark.light} />
                        <Text style={styles.loadingText}>
                            {loading === "ark"
                                ? "Generating Bark address…"
                                : "Generating Bitcoin address…"}
                        </Text>
                    </View>
                )}
            </View>
        </ScreenLayout>
    );
}
