name: Build Release and Upload to TestFlight (iOS)

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  push:
    branches:
      - CB-Production
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 180
    outputs:
      new_build_number: ${{ steps.generate_build_number.outputs.build_number }}
      project_version: ${{ steps.determine_marketing_version.outputs.project_version }}
      latest_commit_message: ${{ steps.get_latest_commit_message.outputs.commit_message }}
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Specify node version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 18

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies with Bundler
        run: bundle install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Clear Derived Data
        run: bundle exec fastlane ios clear_derived_data_lane
        working-directory: ./ios

      - name: Determine Build Number
        id: generate_build_number
        run: echo "::set-output name=build_number::$(date +%Y%m%d%H%M)"

      - name: Determine Marketing Version
        id: determine_marketing_version
        run: |
          VERSION=$(grep -m1 "versionName" android/app/build.gradle | sed 's/.*versionName "\(.*\)"/\1/')
          echo "::set-output name=project_version::$VERSION"

      - name: Get Latest Commit Message
        id: get_latest_commit_message
        run: echo "::set-output name=commit_message::$(git log -1 --pretty=%B)"

      - name: Build iOS
        run: bundle exec fastlane ios build_testflight
        working-directory: ./ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
          CODE_SIGNING_IDENTITY: ${{ secrets.CODE_SIGNING_IDENTITY }}
          DEPLOYMENT_TARGET: ${{ secrets.DEPLOYMENT_TARGET }}

      - name: Upload build number and version
        run: |
          echo "Build Number: ${{ steps.generate_build_number.outputs.build_number }}"
          echo "Version: ${{ steps.determine_marketing_version.outputs.project_version }}"
          echo "Commit: ${{ steps.get_latest_commit_message.outputs.commit_message }}"
